name: Patch Boot with KernelSU

on:
  workflow_dispatch:
    inputs:
      boot_id:
        description: "ID твоего файла на Google Drive"
        required: true
        default: "1lMs6TFkuuN-FxXgwpkV6cAPLd71BYVMf"
      ksu_version:
        description: "Версия KernelSU"
        required: true
        default: "v0.9.5"

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y cpio curl unzip python3-pip
          # Устанавливаем gdown для надежного скачивания с Google Drive
          pip3 install gdown

      - name: Download Boot
        run: |
          # Скачиваем файл по ID
          gdown --id ${{ github.event.inputs.boot_id }} -O boot.img
          
          # Проверка: если файл не скачался, gdown выдаст ошибку
          if [ ! -s boot.img ]; then
            echo "Ошибка: Не удалось скачать файл. Проверь ID и доступ!"
            exit 1
          fi
          echo "Файл успешно скачан, размер: $(stat -c%s "boot.img") байт"

      - name: Download Tools
        run: |
          curl -L "https://github.com/magisk-modules/magiskboot-binaries/releases/download/v27.0/magiskboot.zip" -o magiskboot.zip
          unzip -j magiskboot.zip x86_64/magiskboot -d . && chmod +x magiskboot
          curl -L "https://github.com/tiann/KernelSU/releases/download/${{ github.event.inputs.ksu_version }}/kernel-arm64-414-release.img" -o ksu_kernel

      - name: Patching Image
        run: |
          ./magiskboot unpack boot.img
          if [ ! -f kernel ]; then echo "Ошибка распаковки!"; exit 1; fi
          mv -f ksu_kernel kernel
          ./magiskboot repack boot.img patched_boot.img

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: KSU_Patched_Boot_A50
          path: patched_boot.img
